export { Game } from './game'
export type { GameOptions, UpdateFn, ParamOverrides } from './game'
export { Entity } from './entity'
export { Component } from './component'
export type { ComponentClass, ParamSpec } from './component'
export { Input, DEFAULT_BINDINGS } from './input'
export type { ActionName, InputBindings } from './input'
export { Stats } from './stats'
export type { StatValue } from './stats'
export { GameUi } from './ui'
export { Sprite } from './components/sprite'
export { Solid } from './components/solid'
export { Hitbox } from './components/hitbox'
export { AnimatedSprite } from './components/animated-sprite'
export { aabbOverlap } from './aabb'
export { Emitter } from './events'
export { loadScene, spawnFromJson, resolveEntityComponents } from './scene'
export type { SceneJson, SceneEntityJson, SceneComponentJson, SceneRegistry, PrefabJson } from './scene'
export { ClipPlayer } from './animation/clip-player'
export type { ClipDef } from './animation/clip-player'
export { resolveClip, missingClips } from './animation/contract'
export type { AnimationContract } from './animation/contract'

// Explicit escape hatch while our own API grows: a single source of three
// for the whole workspace. The thesis is that three stays an implementation detail.
export * as THREE from 'three'
