// @vitest-environment node
import { describe, expect, it } from 'vitest'
import tree from '../art/tree.glb?inline'

type Vec3 = [number, number, number]

interface GlbJson {
  meshes: { primitives: { attributes: { POSITION: number; NORMAL: number } }[] }[]
  accessors: { bufferView: number; count: number }[]
  bufferViews: { byteOffset: number; byteLength: number }[]
}

const subtract = (a: Vec3, b: Vec3): Vec3 => [a[0] - b[0], a[1] - b[1], a[2] - b[2]]
const dot = (a: Vec3, b: Vec3): number => a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
const cross = (a: Vec3, b: Vec3): Vec3 => [a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0]]

/** The glb's JSON chunk and its binary chunk, from the data URI Vite inlines the file as. */
function parseGlb(): { json: GlbJson; binary: Uint8Array } {
  const bytes = Uint8Array.from(atob(tree.slice(tree.indexOf(',') + 1)), (char) => char.charCodeAt(0))
  const view = new DataView(bytes.buffer)
  const jsonLength = view.getUint32(12, true)
  const json = JSON.parse(new TextDecoder().decode(bytes.subarray(20, 20 + jsonLength))) as GlbJson
  const binaryStart = 20 + jsonLength + 8
  return { json, binary: bytes.subarray(binaryStart, binaryStart + view.getUint32(20 + jsonLength, true)) }
}

/** One VEC3 float accessor as vectors. */
function vectors(glb: { json: GlbJson; binary: Uint8Array }, accessorIndex: number): Vec3[] {
  const accessor = glb.json.accessors[accessorIndex]
  const view = accessor && glb.json.bufferViews[accessor.bufferView]
  if (!accessor || !view) throw new Error(`no accessor ${accessorIndex}`)
  const data = new DataView(glb.binary.buffer, glb.binary.byteOffset + view.byteOffset, view.byteLength)
  return Array.from({ length: accessor.count }, (_, index): Vec3 => [
    data.getFloat32(index * 12, true),
    data.getFloat32(index * 12 + 4, true),
    data.getFloat32(index * 12 + 8, true),
  ])
}

describe('examples/smoke-3d/art/tree.glb (generated by scripts/generate-smoke-3d-model.mjs)', () => {
  const glb = parseGlb()
  const primitives = glb.json.meshes.flatMap((mesh) => mesh.primitives)

  it('holds the trunk and the foliage as two primitives', () => {
    expect(primitives).toHaveLength(2)
  })

  it.each([0, 1])('winds every triangle of primitive %i counter-clockwise seen from outside, with a matching stored normal', (which) => {
    const primitive = primitives[which]
    if (!primitive) throw new Error(`no primitive ${which}`)
    const positions = vectors(glb, primitive.attributes.POSITION)
    const normals = vectors(glb, primitive.attributes.NORMAL)
    const lows = [0, 1, 2].map((axis) => Math.min(...positions.map((p) => p[axis] ?? 0)))
    const highs = [0, 1, 2].map((axis) => Math.max(...positions.map((p) => p[axis] ?? 0)))
    // Both shapes are convex, so a face is outward when its normal points away from the middle of the shape.
    const centre: Vec3 = [0, 1, 2].map((axis) => ((lows[axis] ?? 0) + (highs[axis] ?? 0)) / 2) as Vec3
    expect(positions.length % 3).toBe(0)
    for (let first = 0; first < positions.length; first += 3) {
      const [a, b, c] = [positions[first], positions[first + 1], positions[first + 2]]
      const stored = normals[first]
      if (!a || !b || !c || !stored) throw new Error(`triangle at vertex ${first} is incomplete`)
      const geometric = cross(subtract(b, a), subtract(c, a))
      const middle: Vec3 = [(a[0] + b[0] + c[0]) / 3, (a[1] + b[1] + c[1]) / 3, (a[2] + b[2] + c[2]) / 3]
      expect(dot(geometric, subtract(middle, centre)), `triangle ${first / 3} faces inward`).toBeGreaterThan(0)
      expect(dot(geometric, stored), `triangle ${first / 3}'s stored normal disagrees with its winding`).toBeGreaterThan(0)
    }
  })
})
