import { access, mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { PrefabJson, RoleDefinition, SceneComponentJson } from '@waica/engine'
import { activeArchetypeId, discoverArchetypes, pickArchetype } from './archetypes.js'
import { WaicaToolError, assertSafeSlug } from './project-path.js'

function nameWords(name: string): string[] {
  return name
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
}

export function componentClassName(name: string): string {
  const words = nameWords(name)
  const value = words.map((word) => word[0]?.toUpperCase() + word.slice(1)).join('')
  if (!/^[A-Za-z][A-Za-z0-9]*$/.test(value)) {
    throw new Error('Component names must start with a letter and use letters or numbers.')
  }
  if (value === 'Component') {
    throw new Error('"Component" is the engine base class — pick another name.')
  }
  return value
}

function componentFilePath(name: string): string {
  const words = nameWords(name)
  componentClassName(name)
  return `src/components/${words.map((word) => word.toLowerCase()).join('-')}.ts`
}

function componentTemplate(name: string): string {
  const Class = componentClassName(name)
  return `import { Component } from '@waica/engine'

// Project-owned behavior — loaded by the shipped game and editor Play.
export class ${Class} extends Component {
  static override componentName = '${Class}'

  override onUpdate(dt: number): void {
    // Add this component's per-frame behavior here.
    void dt
  }
}
`
}

function roleTemplate(role: string): string {
  return `import { defineRole } from '@waica/engine'

// The "${role}" role — generated by waica.
// A role is a character's whole behavior package: a plain-language
// description for the editor, the driver component its states move,
// the starter state graph, and the state code itself.
defineRole('${role}', {
  description: 'Describe what a ${role} does — shown when picking roles.',
  // driver: 'PlatformerMotor', // uncomment if the states move a driver component
  graph: {
    initial: 'idle',
    states: { idle: { transitions: [] } },
  },
  states: {
    idle: {
      onUpdate({ entity, game, fsm }, dt) {
        // Runs every frame while a "${role}" is in its "idle" state.
      },
    },
  },
})
`
}

function stateTemplate(role: string, state: string): string {
  if (role === 'player') {
    return `import { defineStates } from '@waica/engine'
import { PlatformerMotor } from '@waica/behaviors'

// Code for the "${state}" state — generated by waica.
// When it starts, when it ends and which clip it plays live in the
// prefab's State Machine data. While in it, the body keeps the role's
// stock update (running, gravity, collisions, land/fall signals), so
// this file only says what makes "${state}" special.
defineStates('${role}', {
  ${state}: {
    onEnter({ entity }) {
      const motor = entity.get(PlatformerMotor)
      if (!motor) return
      // One burst in the facing direction — replace with your state's idea.
      motor.vx = motor.facing * 30
    },
  },
})
`
  }
  return `import { defineStates } from '@waica/engine'

// Code for the "${state}" state — generated by waica.
// When it starts and when it ends live in the prefab's State Machine
// data; this file is only the behavior. Hooks receive { entity, game, fsm }.
defineStates('${role}', {
  ${state}: {
    onEnter({ entity }) {
      console.log(\`\${entity.name} entered "${state}"\`)
    },
  },
})
`
}

type PrefabType = PrefabJson['type']

/**
 * Prefab directory under src/ per type — the editor's PREFAB_DIRS read the
 * other way round. Duplicated here for the same reason every template above
 * is: the published server cannot import the private editor package, so a
 * parity test holds the two copies together instead of the type system.
 */
const PREFAB_DIRECTORIES: Readonly<Record<PrefabType, string>> = {
  character: 'characters',
  object: 'objects',
  tile: 'tiles',
}

const IDENTITIES = ['player', 'enemy', 'npc', 'custom'] as const
type CharacterIdentity = (typeof IDENTITIES)[number]

const DEFAULT_SPRITE = { width: 1, height: 1, color: 0x8ecae6 }

/** Mirrors the editor's IDENTITY_EXTRAS: what an identity is born with. */
const IDENTITY_EXTRAS: Readonly<Record<CharacterIdentity, readonly SceneComponentJson[]>> = {
  player: [
    { type: 'Respawnable' },
    { type: 'Health', props: { invulnerability: 1 } },
    { type: 'OutOfBounds' },
  ],
  enemy: [{ type: 'Hazard' }, { type: 'Health', props: { max: 1 } }],
  npc: [],
  custom: [],
}

/**
 * The editor's newPrefabComponents, with the role handed in instead of read
 * from the engine's global registry — this server resolves the archetype
 * itself and never installs a bundle into its own process.
 */
function prefabComponents(
  type: PrefabType,
  role: string,
  definition: RoleDefinition | undefined,
  identity?: CharacterIdentity,
): SceneComponentJson[] {
  switch (type) {
    case 'character': {
      const driver: SceneComponentJson[] = definition?.driver ? [{ type: definition.driver }] : []
      return [
        { type: 'Sprite', props: { ...DEFAULT_SPRITE, layer: 2 } },
        {
          type: 'StateMachine',
          props: {
            role,
            initial: definition?.graph?.initial ?? '',
            states: definition?.graph?.states ?? {},
          },
        },
        ...driver,
        ...(identity ? IDENTITY_EXTRAS[identity] : []),
        { type: 'Hitbox', props: { width: 0.9, height: 0.95 } },
      ]
    }
    case 'object':
      return [
        { type: 'Sprite', props: { ...DEFAULT_SPRITE, layer: 1 } },
        { type: 'Hitbox', props: { width: 1, height: 1 } },
      ]
    case 'tile':
      return [
        { type: 'Sprite', props: { ...DEFAULT_SPRITE } },
        { type: 'Solid', props: { width: 1, height: 1 } },
      ]
  }
}

/** The active archetype's roles — the only ones a scaffolded character may adopt. */
async function archetypeRoles(projectPath: string): Promise<Record<string, RoleDefinition>> {
  const activeId = await activeArchetypeId(projectPath)
  const available = await discoverArchetypes(
    projectPath,
    undefined,
    [],
    activeId ? [activeId] : [],
  )
  return pickArchetype(available, activeId, projectPath).manifest.bundle.roles
}

function invalidInput(projectPath: string, message: string): WaicaToolError {
  return new WaicaToolError({ code: 'invalid-input', message, projectPath })
}

const UI_TEMPLATE = `<style>
  .my-ui {
    position: absolute;
    top: 12px;
    left: 12px;
    font: 600 20px system-ui, sans-serif;
    color: #fff;
  }
</style>
<div class="my-ui">✨ {{points}}</div>
`

async function writeOnce(
  projectPath: string,
  relative: string,
  contents: string,
): Promise<{ path: string; created: boolean; reason?: 'exists' }> {
  const target = path.join(projectPath, relative)
  try {
    await access(target)
    return { path: relative, created: false, reason: 'exists' }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
  await mkdir(path.dirname(target), { recursive: true })
  await writeFile(target, contents)
  return { path: relative, created: true }
}

export async function scaffoldComponent(
  projectPath: string,
  name: string,
): Promise<{ path: string; created: boolean; reason?: 'exists'; className: string }> {
  const className = componentClassName(name)
  return { ...(await writeOnce(projectPath, componentFilePath(name), componentTemplate(name))), className }
}

/**
 * A starter prefab of the given type, byte-identical to what the editor
 * writes for the same inputs. The caller names it: no auto-numbering, and an
 * existing file is left exactly as it is.
 */
export async function scaffoldPrefab(
  projectPath: string,
  name: string,
  type: string,
  role?: string,
  identity?: string,
): Promise<{ path: string; created: boolean; reason?: 'exists' }> {
  assertSafeSlug(name, 'name')
  const directory = PREFAB_DIRECTORIES[type as PrefabType]
  if (!directory) {
    throw invalidInput(
      projectPath,
      `type must be one of ${Object.keys(PREFAB_DIRECTORIES).join(', ')}.`,
    )
  }
  const prefabType = type as PrefabType
  if (prefabType !== 'character' && (role !== undefined || identity !== undefined)) {
    throw invalidInput(
      projectPath,
      `role and identity are character-only: a ${prefabType} prefab has neither.`,
    )
  }
  if (identity !== undefined && !(IDENTITIES as readonly string[]).includes(identity)) {
    throw invalidInput(projectPath, `identity must be one of ${IDENTITIES.join(', ')}.`)
  }
  let definition: RoleDefinition | undefined
  // Same default the editor's creation dialog starts from.
  const roleName = role ?? 'player'
  if (prefabType === 'character') {
    const roles = await archetypeRoles(projectPath)
    definition = roles[roleName]
    if (!definition) {
      // Falling back to an empty graph would write a character that stands
      // still in Play and says nothing about why.
      throw new WaicaToolError({
        code: 'unknown-role',
        message: `Unknown role "${roleName}". Available roles: ${Object.keys(roles).sort().join(', ')}.`,
        projectPath,
        available: Object.keys(roles).sort(),
      })
    }
  }
  const prefab: PrefabJson = {
    waicaPrefab: 1,
    type: prefabType,
    components: prefabComponents(
      prefabType,
      roleName,
      definition,
      identity as CharacterIdentity | undefined,
    ),
  }
  return writeOnce(
    projectPath,
    `src/${directory}/${name}.${prefabType}.json`,
    JSON.stringify(prefab, null, 2) + '\n',
  )
}

export async function scaffoldRole(
  projectPath: string,
  role: string,
): Promise<{ path: string; created: boolean; reason?: 'exists' }> {
  assertSafeSlug(role, 'role')
  return writeOnce(projectPath, `src/roles/${role}.ts`, roleTemplate(role))
}

export async function scaffoldState(
  projectPath: string,
  role: string,
  state: string,
): Promise<{ path: string; created: boolean; reason?: 'exists' }> {
  assertSafeSlug(role, 'role')
  assertSafeSlug(state, 'state')
  if (!/^[A-Za-z][A-Za-z0-9_]*$/.test(state)) {
    throw new Error('state must be a valid TypeScript identifier because the scaffold uses it as an object key.')
  }
  // Role-agnostic by contract: the editor and shipped runtime both glob the
  // flat src/states/*.ts convention, and the file self-registers its role.
  return writeOnce(projectPath, `src/states/${state}.ts`, stateTemplate(role, state))
}

export async function scaffoldUi(
  projectPath: string,
  name: string,
): Promise<{ path: string; created: boolean; reason?: 'exists' }> {
  assertSafeSlug(name, 'name')
  return writeOnce(projectPath, `src/ui/${name}.html`, UI_TEMPLATE)
}
