import { access, mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { assertSafeSlug } from './project-path.js'

function nameWords(name: string): string[] {
  return name
    .trim()
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
}

export function componentClassName(name: string): string {
  const words = nameWords(name)
  const value = words.map((word) => word[0]?.toUpperCase() + word.slice(1)).join('')
  if (!/^[A-Za-z][A-Za-z0-9]*$/.test(value)) {
    throw new Error('Component names must start with a letter and use letters or numbers.')
  }
  if (value === 'Component') {
    throw new Error('"Component" is the engine base class — pick another name.')
  }
  return value
}

function componentFilePath(name: string): string {
  const words = nameWords(name)
  componentClassName(name)
  return `src/components/${words.map((word) => word.toLowerCase()).join('-')}.ts`
}

function componentTemplate(name: string): string {
  const Class = componentClassName(name)
  return `import { Component } from '@waica/engine'

// Project-owned behavior — loaded by the shipped game and editor Play.
export class ${Class} extends Component {
  static override componentName = '${Class}'

  override onUpdate(dt: number): void {
    // Add this component's per-frame behavior here.
    void dt
  }
}
`
}

function roleTemplate(role: string): string {
  return `import { defineRole } from '@waica/engine'

// The "${role}" role — generated by waica.
// A role is a character's whole behavior package: a plain-language
// description for the editor, the driver component its states move,
// the starter state graph, and the state code itself.
defineRole('${role}', {
  description: 'Describe what a ${role} does — shown when picking roles.',
  // driver: 'PlatformerMotor', // uncomment if the states move a driver component
  graph: {
    initial: 'idle',
    states: { idle: { transitions: [] } },
  },
  states: {
    idle: {
      onUpdate({ entity, game, fsm }, dt) {
        // Runs every frame while a "${role}" is in its "idle" state.
      },
    },
  },
})
`
}

function stateTemplate(role: string, state: string): string {
  if (role === 'player') {
    return `import { defineStates } from '@waica/engine'
import { PlatformerMotor } from '@waica/behaviors'

// Code for the "${state}" state — generated by waica.
// When it starts, when it ends and which clip it plays live in the
// prefab's State Machine data. While in it, the body keeps the role's
// stock update (running, gravity, collisions, land/fall signals), so
// this file only says what makes "${state}" special.
defineStates('${role}', {
  ${state}: {
    onEnter({ entity }) {
      const motor = entity.get(PlatformerMotor)
      if (!motor) return
      // One burst in the facing direction — replace with your state's idea.
      motor.vx = motor.facing * 30
    },
  },
})
`
  }
  return `import { defineStates } from '@waica/engine'

// Code for the "${state}" state — generated by waica.
// When it starts and when it ends live in the prefab's State Machine
// data; this file is only the behavior. Hooks receive { entity, game, fsm }.
defineStates('${role}', {
  ${state}: {
    onEnter({ entity }) {
      console.log(\`\${entity.name} entered "${state}"\`)
    },
  },
})
`
}

const UI_TEMPLATE = `<style>
  .my-ui {
    position: absolute;
    top: 12px;
    left: 12px;
    font: 600 20px system-ui, sans-serif;
    color: #fff;
  }
</style>
<div class="my-ui">✨ {{points}}</div>
`

async function writeOnce(
  projectPath: string,
  relative: string,
  contents: string,
): Promise<{ path: string; created: boolean; reason?: 'exists' }> {
  const target = path.join(projectPath, relative)
  try {
    await access(target)
    return { path: relative, created: false, reason: 'exists' }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
  await mkdir(path.dirname(target), { recursive: true })
  await writeFile(target, contents)
  return { path: relative, created: true }
}

export async function scaffoldComponent(
  projectPath: string,
  name: string,
): Promise<{ path: string; created: boolean; reason?: 'exists'; className: string }> {
  const className = componentClassName(name)
  return { ...(await writeOnce(projectPath, componentFilePath(name), componentTemplate(name))), className }
}

export async function scaffoldRole(
  projectPath: string,
  role: string,
): Promise<{ path: string; created: boolean; reason?: 'exists' }> {
  assertSafeSlug(role, 'role')
  return writeOnce(projectPath, `src/roles/${role}.ts`, roleTemplate(role))
}

export async function scaffoldState(
  projectPath: string,
  role: string,
  state: string,
): Promise<{ path: string; created: boolean; reason?: 'exists' }> {
  assertSafeSlug(role, 'role')
  assertSafeSlug(state, 'state')
  if (!/^[A-Za-z][A-Za-z0-9_]*$/.test(state)) {
    throw new Error('state must be a valid TypeScript identifier because the scaffold uses it as an object key.')
  }
  // Role-agnostic by contract: the editor and shipped runtime both glob the
  // flat src/states/*.ts convention, and the file self-registers its role.
  return writeOnce(projectPath, `src/states/${state}.ts`, stateTemplate(role, state))
}

export async function scaffoldUi(
  projectPath: string,
  name: string,
): Promise<{ path: string; created: boolean; reason?: 'exists' }> {
  assertSafeSlug(name, 'name')
  return writeOnce(projectPath, `src/ui/${name}.html`, UI_TEMPLATE)
}
